### ISSUE TITLE
Question about the point-wise ECE scores in Fig. 2.

### ISSUE THREAD

**Issue by yuan-zm** [ldkong1205/Calib3D#1]
Hi @ldkong1205 ,

Thanks for your great work. 

According to Eqs. 1 and 2 in the main paper and https://github.com/ldkong1205/Calib3D/blob/4ce4a4989134449514c2d52b8aead3ba252e398b/calib_model.py#L135 in the code.  The returned value is a decimal for the input batch. How to get the point-wise ECE scores in Fig. 2?

**Comment by ldkong1205** [comment]
Hi @yuan-zm, sorry for the late reply~

For calculating point-wise ECE, you can simply treat each point as a sample and use the `calculate_ece` function to compute the scores.

After obtaining scores for all points, you can then draw colormaps for the whole point cloud.

Feel free to let me know if the above resolves your question.

**Comment by yuan-zm** [comment]
Hi @ldkong1205,

Thank you for your response. Your explanation completely solves my problem. It's clear to me now.
